// Code generated by protoc-gen-go.
// source: proto/api.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/api.proto
	proto/backend_config.proto
	proto/filesystem.proto
	proto/frontend_config.proto

It has these top-level messages:
	GetNodeRequest
	GetNodeResponse
	BackendConfig
	Node
	FrontendConfig
	TCPProxyRoute
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type GetNodeRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetNodeResponse struct {
	// The meta information about the requested node and its children, if any.
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetNodeResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto1.RegisterType((*GetNodeRequest)(nil), "fproxy.GetNodeRequest")
	proto1.RegisterType((*GetNodeResponse)(nil), "fproxy.GetNodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Backend service

type BackendClient interface {
	// Gets a node's meta information from the backend.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := grpc.Invoke(ctx, "/fproxy.Backend/GetNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Backend service

type BackendServer interface {
	// Gets a node's meta information from the backend.
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BackendServer).GetNode(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fproxy.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _Backend_GetNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03, 0xb3, 0x84, 0xd8, 0xd2, 0x80, 0x74, 0x45, 0xa5, 0x94,
	0x18, 0x44, 0x22, 0x2d, 0x33, 0x27, 0xb5, 0xb8, 0xb2, 0xb8, 0x24, 0x35, 0x17, 0x22, 0xaf, 0xa4,
	0xc2, 0xc5, 0xe7, 0x9e, 0x5a, 0xe2, 0x97, 0x9f, 0x92, 0x1a, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c,
	0x22, 0x24, 0xc4, 0xc5, 0x52, 0x90, 0x58, 0x92, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0x66, 0x2b, 0x19, 0x73, 0xf1, 0xc3, 0x55, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x29, 0x70,
	0xb1, 0xe4, 0x01, 0xf9, 0x60, 0x65, 0xdc, 0x46, 0x3c, 0x7a, 0x10, 0x7b, 0xf4, 0xc0, 0x6a, 0xc0,
	0x32, 0x46, 0xae, 0x5c, 0xec, 0x4e, 0x89, 0xc9, 0xd9, 0xa9, 0x79, 0x29, 0x42, 0x56, 0x5c, 0xec,
	0x50, 0xfd, 0x42, 0x62, 0x30, 0x95, 0xa8, 0xd6, 0x4a, 0x89, 0x63, 0x88, 0x43, 0x2c, 0x72, 0x62,
	0x8f, 0x62, 0x05, 0x3b, 0x35, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x5f, 0xfa, 0x93, 0xe4, 0x00, 0x00, 0x00,
}
