// Code generated by protoc-gen-go.
// source: proto/frontend_config.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FrontendConfig struct {
	TcpProxyRoute      []*TCPProxyRoute          `protobuf:"bytes,1,rep,name=tcp_proxy_route" json:"tcp_proxy_route,omitempty"`
	Server             *FrontendConfig_Server    `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Backend            []*FrontendConfig_Backend `protobuf:"bytes,3,rep,name=backend" json:"backend,omitempty"`
	OauthConfig        *OauthConfig              `protobuf:"bytes,4,opt,name=oauth_config" json:"oauth_config,omitempty"`
	AuthCookieKey      []byte                    `protobuf:"bytes,5,opt,name=auth_cookie_key,proto3" json:"auth_cookie_key,omitempty"`
	AuthCookieInsecure bool                      `protobuf:"varint,6,opt,name=auth_cookie_insecure" json:"auth_cookie_insecure,omitempty"`
	EmailToUserId      map[string]string         `protobuf:"bytes,7,rep,name=email_to_user_id" json:"email_to_user_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FrontendConfig) Reset()                    { *m = FrontendConfig{} }
func (m *FrontendConfig) String() string            { return proto1.CompactTextString(m) }
func (*FrontendConfig) ProtoMessage()               {}
func (*FrontendConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *FrontendConfig) GetTcpProxyRoute() []*TCPProxyRoute {
	if m != nil {
		return m.TcpProxyRoute
	}
	return nil
}

func (m *FrontendConfig) GetServer() *FrontendConfig_Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *FrontendConfig) GetBackend() []*FrontendConfig_Backend {
	if m != nil {
		return m.Backend
	}
	return nil
}

func (m *FrontendConfig) GetOauthConfig() *OauthConfig {
	if m != nil {
		return m.OauthConfig
	}
	return nil
}

func (m *FrontendConfig) GetEmailToUserId() map[string]string {
	if m != nil {
		return m.EmailToUserId
	}
	return nil
}

// TODO: this is repeated 3 different times between frontend and backend
// config. Consolidate them.
type FrontendConfig_Server struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	// Types that are valid to be assigned to Security:
	//	*FrontendConfig_Server_Tls
	//	*FrontendConfig_Server_Insecure
	Security isFrontendConfig_Server_Security `protobuf_oneof:"security"`
}

func (m *FrontendConfig_Server) Reset()                    { *m = FrontendConfig_Server{} }
func (m *FrontendConfig_Server) String() string            { return proto1.CompactTextString(m) }
func (*FrontendConfig_Server) ProtoMessage()               {}
func (*FrontendConfig_Server) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

type isFrontendConfig_Server_Security interface {
	isFrontendConfig_Server_Security()
}

type FrontendConfig_Server_Tls struct {
	Tls *TLSConfig `protobuf:"bytes,2,opt,name=tls,oneof"`
}
type FrontendConfig_Server_Insecure struct {
	Insecure bool `protobuf:"varint,3,opt,name=insecure,oneof"`
}

func (*FrontendConfig_Server_Tls) isFrontendConfig_Server_Security()      {}
func (*FrontendConfig_Server_Insecure) isFrontendConfig_Server_Security() {}

func (m *FrontendConfig_Server) GetSecurity() isFrontendConfig_Server_Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *FrontendConfig_Server) GetTls() *TLSConfig {
	if x, ok := m.GetSecurity().(*FrontendConfig_Server_Tls); ok {
		return x.Tls
	}
	return nil
}

func (m *FrontendConfig_Server) GetInsecure() bool {
	if x, ok := m.GetSecurity().(*FrontendConfig_Server_Insecure); ok {
		return x.Insecure
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FrontendConfig_Server) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _FrontendConfig_Server_OneofMarshaler, _FrontendConfig_Server_OneofUnmarshaler, _FrontendConfig_Server_OneofSizer, []interface{}{
		(*FrontendConfig_Server_Tls)(nil),
		(*FrontendConfig_Server_Insecure)(nil),
	}
}

func _FrontendConfig_Server_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*FrontendConfig_Server)
	// security
	switch x := m.Security.(type) {
	case *FrontendConfig_Server_Tls:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Tls); err != nil {
			return err
		}
	case *FrontendConfig_Server_Insecure:
		t := uint64(0)
		if x.Insecure {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto1.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("FrontendConfig_Server.Security has unexpected type %T", x)
	}
	return nil
}

func _FrontendConfig_Server_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*FrontendConfig_Server)
	switch tag {
	case 2: // security.tls
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(TLSConfig)
		err := b.DecodeMessage(msg)
		m.Security = &FrontendConfig_Server_Tls{msg}
		return true, err
	case 3: // security.insecure
		if wire != proto1.WireVarint {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Security = &FrontendConfig_Server_Insecure{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _FrontendConfig_Server_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*FrontendConfig_Server)
	// security
	switch x := m.Security.(type) {
	case *FrontendConfig_Server_Tls:
		s := proto1.Size(x.Tls)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *FrontendConfig_Server_Insecure:
		n += proto1.SizeVarint(3<<3 | proto1.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FrontendConfig_Backend struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	// Types that are valid to be assigned to Security:
	//	*FrontendConfig_Backend_Tls
	//	*FrontendConfig_Backend_Insecure
	Security isFrontendConfig_Backend_Security `protobuf_oneof:"security"`
}

func (m *FrontendConfig_Backend) Reset()                    { *m = FrontendConfig_Backend{} }
func (m *FrontendConfig_Backend) String() string            { return proto1.CompactTextString(m) }
func (*FrontendConfig_Backend) ProtoMessage()               {}
func (*FrontendConfig_Backend) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 1} }

type isFrontendConfig_Backend_Security interface {
	isFrontendConfig_Backend_Security()
}

type FrontendConfig_Backend_Tls struct {
	Tls *TLSConfig `protobuf:"bytes,3,opt,name=tls,oneof"`
}
type FrontendConfig_Backend_Insecure struct {
	Insecure bool `protobuf:"varint,4,opt,name=insecure,oneof"`
}

func (*FrontendConfig_Backend_Tls) isFrontendConfig_Backend_Security()      {}
func (*FrontendConfig_Backend_Insecure) isFrontendConfig_Backend_Security() {}

func (m *FrontendConfig_Backend) GetSecurity() isFrontendConfig_Backend_Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *FrontendConfig_Backend) GetTls() *TLSConfig {
	if x, ok := m.GetSecurity().(*FrontendConfig_Backend_Tls); ok {
		return x.Tls
	}
	return nil
}

func (m *FrontendConfig_Backend) GetInsecure() bool {
	if x, ok := m.GetSecurity().(*FrontendConfig_Backend_Insecure); ok {
		return x.Insecure
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FrontendConfig_Backend) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _FrontendConfig_Backend_OneofMarshaler, _FrontendConfig_Backend_OneofUnmarshaler, _FrontendConfig_Backend_OneofSizer, []interface{}{
		(*FrontendConfig_Backend_Tls)(nil),
		(*FrontendConfig_Backend_Insecure)(nil),
	}
}

func _FrontendConfig_Backend_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*FrontendConfig_Backend)
	// security
	switch x := m.Security.(type) {
	case *FrontendConfig_Backend_Tls:
		b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Tls); err != nil {
			return err
		}
	case *FrontendConfig_Backend_Insecure:
		t := uint64(0)
		if x.Insecure {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto1.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("FrontendConfig_Backend.Security has unexpected type %T", x)
	}
	return nil
}

func _FrontendConfig_Backend_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*FrontendConfig_Backend)
	switch tag {
	case 3: // security.tls
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(TLSConfig)
		err := b.DecodeMessage(msg)
		m.Security = &FrontendConfig_Backend_Tls{msg}
		return true, err
	case 4: // security.insecure
		if wire != proto1.WireVarint {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Security = &FrontendConfig_Backend_Insecure{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _FrontendConfig_Backend_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*FrontendConfig_Backend)
	// security
	switch x := m.Security.(type) {
	case *FrontendConfig_Backend_Tls:
		s := proto1.Size(x.Tls)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *FrontendConfig_Backend_Insecure:
		n += proto1.SizeVarint(4<<3 | proto1.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TCPProxyRoute struct {
	Listen string `protobuf:"bytes,1,opt,name=listen" json:"listen,omitempty"`
	Dial   string `protobuf:"bytes,2,opt,name=dial" json:"dial,omitempty"`
}

func (m *TCPProxyRoute) Reset()                    { *m = TCPProxyRoute{} }
func (m *TCPProxyRoute) String() string            { return proto1.CompactTextString(m) }
func (*TCPProxyRoute) ProtoMessage()               {}
func (*TCPProxyRoute) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type OauthConfig struct {
	ClientId     string `protobuf:"bytes,1,opt,name=client_id" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret" json:"client_secret,omitempty"`
	RedirectUrl  string `protobuf:"bytes,3,opt,name=redirect_url" json:"redirect_url,omitempty"`
}

func (m *OauthConfig) Reset()                    { *m = OauthConfig{} }
func (m *OauthConfig) String() string            { return proto1.CompactTextString(m) }
func (*OauthConfig) ProtoMessage()               {}
func (*OauthConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func init() {
	proto1.RegisterType((*FrontendConfig)(nil), "fproxy.FrontendConfig")
	proto1.RegisterType((*FrontendConfig_Server)(nil), "fproxy.FrontendConfig.Server")
	proto1.RegisterType((*FrontendConfig_Backend)(nil), "fproxy.FrontendConfig.Backend")
	proto1.RegisterType((*TCPProxyRoute)(nil), "fproxy.TCPProxyRoute")
	proto1.RegisterType((*OauthConfig)(nil), "fproxy.OauthConfig")
}

var fileDescriptor2 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0xe2, 0x24, 0x93, 0x98, 0x94, 0xa1, 0x20, 0x2b, 0x05, 0x54, 0x82, 0x40, 0xe5,
	0x12, 0x10, 0x08, 0x54, 0x81, 0x90, 0x50, 0xaa, 0x22, 0x22, 0x90, 0xa8, 0x36, 0xed, 0x85, 0x8b,
	0xe5, 0xda, 0x1b, 0xba, 0x8a, 0xeb, 0x8d, 0x36, 0xeb, 0x0a, 0x5f, 0xf9, 0x9d, 0xfc, 0x18, 0xf6,
	0xcb, 0x49, 0x2a, 0x28, 0x52, 0x4f, 0x9e, 0x7d, 0xf3, 0xde, 0xce, 0x9b, 0x99, 0x35, 0xec, 0x2e,
	0x04, 0x97, 0xfc, 0xc5, 0x4c, 0xf0, 0x42, 0xd2, 0x22, 0x8b, 0x53, 0x5e, 0xcc, 0xd8, 0x8f, 0x91,
	0x41, 0x31, 0x98, 0xa9, 0xef, 0xcf, 0x6a, 0xd0, 0xb7, 0x24, 0x99, 0x2f, 0x6d, 0x62, 0xf8, 0xbb,
	0x09, 0xb7, 0x3f, 0x39, 0xc9, 0xa1, 0x51, 0xe0, 0x07, 0xe8, 0xcb, 0x74, 0x11, 0x1b, 0x41, 0x2c,
	0x78, 0x29, 0x69, 0xe4, 0xed, 0xf9, 0xfb, 0xdd, 0x57, 0xf7, 0x46, 0xf6, 0x96, 0xd1, 0xc9, 0xe1,
	0xf1, 0xb1, 0x0e, 0x88, 0x4e, 0x92, 0x50, 0xb1, 0xd7, 0x47, 0x7c, 0x03, 0xc1, 0x92, 0x8a, 0x4b,
	0x2a, 0xa2, 0xad, 0x3d, 0x4f, 0xa9, 0x1e, 0xd6, 0xaa, 0xab, 0x65, 0x46, 0x53, 0x43, 0x22, 0x8e,
	0x8c, 0x07, 0xd0, 0x3a, 0x4b, 0xd2, 0xb9, 0xca, 0x47, 0xbe, 0xa9, 0xf6, 0xe8, 0x1a, 0xdd, 0xd8,
	0xb2, 0x48, 0x4d, 0xc7, 0xb7, 0xd0, 0xe3, 0x49, 0x29, 0xcf, 0x5d, 0xc7, 0x51, 0xc3, 0x94, 0xbd,
	0x5b, 0xcb, 0xbf, 0xe9, 0x9c, 0xd5, 0x92, 0x2e, 0x5f, 0x1f, 0xf0, 0x19, 0xf4, 0x9d, 0x8c, 0xcf,
	0x19, 0x8d, 0xe7, 0xb4, 0x8a, 0x9a, 0x4a, 0xda, 0x23, 0xa1, 0x25, 0x69, 0xf4, 0x0b, 0xad, 0xf0,
	0x25, 0xec, 0x6c, 0xf2, 0x58, 0xb1, 0xa4, 0x69, 0x29, 0x68, 0x14, 0x28, 0x72, 0x9b, 0xe0, 0x9a,
	0x3c, 0x71, 0x19, 0x24, 0xb0, 0x4d, 0x2f, 0x12, 0x96, 0xc7, 0x92, 0xc7, 0xa5, 0xea, 0x2f, 0x66,
	0x59, 0xd4, 0x32, 0x4d, 0x3d, 0xbf, 0xa6, 0xa9, 0x23, 0x4d, 0x3f, 0xe1, 0xa7, 0x8a, 0x3c, 0xc9,
	0x8e, 0x0a, 0x29, 0x2a, 0x12, 0xd2, 0x4d, 0x6c, 0x70, 0x01, 0x81, 0x9d, 0x18, 0x22, 0x34, 0x92,
	0x2c, 0x13, 0x6a, 0x29, 0xde, 0x7e, 0x87, 0x98, 0x18, 0x9f, 0x82, 0xaf, 0x76, 0xea, 0x26, 0x7e,
	0x67, 0xb5, 0xa7, 0xaf, 0x53, 0x7b, 0xff, 0xe7, 0x5b, 0x44, 0xe7, 0xf1, 0x01, 0xb4, 0x57, 0xf6,
	0x7d, 0x6d, 0x5f, 0x25, 0x56, 0xc8, 0x18, 0xa0, 0x6d, 0x22, 0x26, 0xab, 0xc1, 0x2f, 0x0f, 0x5a,
	0x6e, 0xd2, 0xff, 0x2c, 0xa8, 0xb0, 0x45, 0x22, 0xcf, 0x4d, 0x45, 0x85, 0xe9, 0xb8, 0x36, 0xe1,
	0xdf, 0xc0, 0x44, 0xe3, 0xbf, 0x26, 0x3e, 0x02, 0xfe, 0x3d, 0x18, 0xdc, 0x06, 0x5f, 0xef, 0xca,
	0xba, 0xd1, 0x21, 0xee, 0x40, 0xf3, 0x32, 0xc9, 0x4b, 0xea, 0xdc, 0xd8, 0xc3, 0xbb, 0xad, 0x03,
	0x6f, 0xf8, 0x1e, 0xc2, 0x2b, 0x8f, 0x15, 0xef, 0x43, 0x90, 0xb3, 0xa5, 0x9a, 0xbc, 0xd3, 0xbb,
	0x93, 0xee, 0x27, 0x63, 0x49, 0x5e, 0xf7, 0xa3, 0xe3, 0xa1, 0x80, 0xee, 0xc6, 0xe3, 0xc1, 0x5d,
	0xe8, 0xa4, 0x39, 0xa3, 0x85, 0xd4, 0xeb, 0xb4, 0xea, 0xb6, 0x05, 0x26, 0x19, 0x3e, 0x81, 0xd0,
	0x25, 0x95, 0x7b, 0x41, 0xa5, 0xbb, 0xa8, 0x67, 0xc1, 0xa9, 0xc1, 0xf0, 0x31, 0xf4, 0x04, 0xcd,
	0x98, 0xa0, 0xa9, 0x8c, 0x4b, 0x91, 0x9b, 0x49, 0x75, 0x48, 0xb7, 0xc6, 0x4e, 0x45, 0x3e, 0x6e,
	0x7d, 0x6f, 0x9a, 0x1f, 0xf3, 0x2c, 0x30, 0x9f, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf0,
	0x1d, 0xfd, 0xe6, 0xd7, 0x03, 0x00, 0x00,
}
